apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: olubyw7ee-python
  janus-idp.io/tekton: olubyw7ee-python
  backstage.io/kubernetes-id: olubyw7ee-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: olubyw7ee-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
